#!/usr/bin/env python3
"""Emit ordinary ring-identity replay obligations from accepted JSON evidence.

Emission is NOT compilation. The resulting identities deliberately do not
claim that the complete source-language programs have been extracted correctly.
"""
from pathlib import Path
import json
from verify_stdlib import read_json,check_certificate

ROOT=Path(__file__).resolve().parents[1]

def expr(poly,vs):
    terms=[]
    for powers,(num,den) in poly:
        coeff=f'({num} : ℚ)' if den=='1' else f'(({num} : ℚ) / {den})'
        factors=[coeff]
        for v,e in zip(vs,powers,strict=True):
            if e:factors.append(f'({v})' if e==1 else f'({v}) ^ {e}')
        terms.append('('+' * '.join(factors)+')')
    return ' + '.join(terms) if terms else '(0 : ℚ)'

def combination(hs,gs,hvs,gvs):
    return ' + '.join(f'({expr(h,hvs)}) * ({expr(g,gvs)})' for h,g in zip(hs,gs,strict=True)) or '(0 : ℚ)'

def main():
    out=['import Mathlib','',
         '/- Generated by prototype/emit_lean.py from independently replayed certificates.',
         '   STATUS: NOT COMPILED. These are polynomial identity obligations only. -/',
         'set_option autoImplicit false','namespace ForgeRelationalClosure.Generated','']
    count=0;cases=0
    for ep in sorted((ROOT/'results/experiment/evidence').glob('*.ideal.json')):
        cert=read_json(ep)
        if cert['schema']!='forge-closure-cert-v1':continue
        name=ep.name.rsplit('.',2)[0];p=read_json(ROOT/'results/experiment/problems'/f'{name}.json')
        check_certificate(p,cert);cases+=1
        xs=[f'x{i}' for i in range(p['n'])];ts=[f't{i}' for i in range(p['parameters'])]
        def emit(label,vs,lhs,rhs):
            nonlocal count
            binders=' ('+' '.join(vs)+' : ℚ)' if vs else ''
            out.extend([f'theorem {name}_{label}{binders} :',f'    ({lhs}) =',f'    ({rhs}) := by','  ring',''])
            count+=1
        for bi,b in enumerate(p['initial']):
            vals=[expr(q,ts) for q in b['state']]
            for j,g in enumerate(cert['basis'][b['location']]):
                emit(f'base_{bi}_{j}',ts,expr(g,vals),'0')
        for ti,target in enumerate(p['targets']):
            gs=cert['basis'][target['location']]
            emit(f'target_{ti}',xs,expr(target['polynomial'],xs),combination(cert['target'][ti],gs,xs,xs))
        for ei,e in enumerate(p['edges']):
            us=[f'u{i}' for i in range(e['inputs'])];vs=xs+us
            F=[expr(f,vs) for f in e['update']]
            for gi,g in enumerate(cert['basis'][e['dst']]):
                emit(f'step_{ei}_{gi}',vs,expr(g,F),
                     combination(cert['step'][ei][gi],cert['basis'][e['src']],vs,xs))
    out.append('end ForgeRelationalClosure.Generated')
    (ROOT/'lean/GeneratedIdentities.lean').write_text('\n'.join(out)+'\n')
    manifest=dict(cases=cases,identities=count,status='GENERATED_NOT_COMPILED',
                  source='accepted ideal certificates',complete_source_goal_proofs=False)
    (ROOT/'results/lean-emission.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(json.dumps(manifest))

if __name__=='__main__':main()
