import Forge.Checker.Affine
/-
  GENERATED by tools/export_lean_affine.py from the prototype's certificate
  bundle (family "Integral affine witness"). Do not edit by hand; regenerate.

  Each certificate below was accepted by the prototype's
  `check_affine_witness(A, B, c, W, require_integral=True)` and by an integer
  re-implementation of `AffineCert.check` in the exporter, and is accepted here
  again by the Lean kernel via `decide`. No `native_decide`.

  The `_concrete` theorems are derived from `AffineCert.sound` by unfolding
  definitions with `simp only` and a single arithmetic lemma, `Int.add_zero`;
  no decision procedure proves them.

  Negative controls: the bundle's own mutation, plus controls that each break a
  named half of the checker. For the shape-only controls the file also proves
  that the row identities still hold, so the rejection is attributable to the
  shape test alone.
-/

namespace Forge.Checker.AffineCorpus
open Forge.Checker.Lin Forge.Checker.Affine

/-! ### `integral_affine` --- 2 equations, 2 witness coordinates, 2 parameters -/

def integral_affine_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_c : List Int := [5, (-3)]
def integral_affine_cert : AffineCert := { linear := [[(-1), (-9)], [2, 4]], offset := [11, (-3)] }

/-- The checker accepts, by kernel reduction. -/
theorem integral_affine_checks : integral_affine_cert.check integral_affine_A integral_affine_B integral_affine_c = true := by decide

/-- For every `x`, `w = W x + d` solves `A w = B x + c`. -/
theorem integral_affine_sound (x : List Int) :
    mulVec integral_affine_A (integral_affine_cert.apply x) = vadd (mulVec integral_affine_B x) integral_affine_c :=
  AffineCert.sound _ _ _ _ integral_affine_checks x

/-- The same fact in ordinary arithmetic, with the witness substituted. -/
theorem integral_affine_concrete (x0 x1 : Int) :
    1 * ((-1) * x0 + ((-9) * x1) + 11) + (2 * (2 * x0 + (4 * x1) + (-3))) = (3 * x0 + ((-1) * x1)) + 5 ∧
    0 * ((-1) * x0 + ((-9) * x1) + 11) + (1 * (2 * x0 + (4 * x1) + (-3))) = (2 * x0 + (4 * x1)) + (-3) := by
  have h := integral_affine_sound [x0, x1]
  simp only [integral_affine_A, integral_affine_B, integral_affine_c, integral_affine_cert, AffineCert.apply, mulVec_cons, mulVec_nil,
    dot_cons_cons, dot_nil_right, vadd_cons_cons, vadd_nil_left,
    Int.add_zero, List.cons.injEq] at h
  obtain ⟨h0, h1, -⟩ := h
  exact ⟨h0, h1⟩

/-- Integral Skolem form: for all parameters there is an integer solution. -/
theorem integral_affine_exists (x0 x1 : Int) :
    ∃ w0 w1 : Int, 1 * w0 + (2 * w1) = (3 * x0 + ((-1) * x1)) + 5 ∧ 0 * w0 + (1 * w1) = (2 * x0 + (4 * x1)) + (-3) :=
  ⟨((-1) * x0 + ((-9) * x1) + 11), (2 * x0 + (4 * x1) + (-3)), integral_affine_concrete x0 x1⟩

/-- NEGATIVE CONTROL `mutation_offset0`: the bundle's own mutation, `offset[0] + 1`; breaks `A d = c`.
shapeOK = true, rowsOK = false (checked in Python and below). -/
def integral_affine_mutation_offset0_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_mutation_offset0_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_mutation_offset0_c : List Int := [5, (-3)]
def integral_affine_mutation_offset0_cert : AffineCert := { linear := [[(-1), (-9)], [2, 4]], offset := [12, (-3)] }
theorem integral_affine_mutation_offset0_rejected : integral_affine_mutation_offset0_cert.check integral_affine_mutation_offset0_A integral_affine_mutation_offset0_B integral_affine_mutation_offset0_c = false := by decide
theorem integral_affine_mutation_offset0_halves :
    shapeOK integral_affine_mutation_offset0_A integral_affine_mutation_offset0_B integral_affine_mutation_offset0_c integral_affine_mutation_offset0_cert = true ∧
    rowsOK (integral_affine_mutation_offset0_B.headD []).length integral_affine_mutation_offset0_cert.linear integral_affine_mutation_offset0_cert.offset integral_affine_mutation_offset0_A integral_affine_mutation_offset0_B integral_affine_mutation_offset0_c = false := by decide
#guard integral_affine_mutation_offset0_cert.check integral_affine_mutation_offset0_A integral_affine_mutation_offset0_B integral_affine_mutation_offset0_c = false

/-- NEGATIVE CONTROL `linear_entry`: `W[0][0] + 1`, a column of `A` that is not zero; breaks `A W = B`.
shapeOK = true, rowsOK = false (checked in Python and below). -/
def integral_affine_linear_entry_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_linear_entry_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_linear_entry_c : List Int := [5, (-3)]
def integral_affine_linear_entry_cert : AffineCert := { linear := [[0, (-9)], [2, 4]], offset := [11, (-3)] }
theorem integral_affine_linear_entry_rejected : integral_affine_linear_entry_cert.check integral_affine_linear_entry_A integral_affine_linear_entry_B integral_affine_linear_entry_c = false := by decide
theorem integral_affine_linear_entry_halves :
    shapeOK integral_affine_linear_entry_A integral_affine_linear_entry_B integral_affine_linear_entry_c integral_affine_linear_entry_cert = true ∧
    rowsOK (integral_affine_linear_entry_B.headD []).length integral_affine_linear_entry_cert.linear integral_affine_linear_entry_cert.offset integral_affine_linear_entry_A integral_affine_linear_entry_B integral_affine_linear_entry_c = false := by decide
#guard integral_affine_linear_entry_cert.check integral_affine_linear_entry_A integral_affine_linear_entry_B integral_affine_linear_entry_c = false

/-- NEGATIVE CONTROL `offset_long`: `offset` with an extra trailing 0; the truncating row identities still hold.
shapeOK = false, rowsOK = true (checked in Python and below). -/
def integral_affine_offset_long_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_offset_long_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_offset_long_c : List Int := [5, (-3)]
def integral_affine_offset_long_cert : AffineCert := { linear := [[(-1), (-9)], [2, 4]], offset := [11, (-3), 0] }
theorem integral_affine_offset_long_rejected : integral_affine_offset_long_cert.check integral_affine_offset_long_A integral_affine_offset_long_B integral_affine_offset_long_c = false := by decide
theorem integral_affine_offset_long_halves :
    shapeOK integral_affine_offset_long_A integral_affine_offset_long_B integral_affine_offset_long_c integral_affine_offset_long_cert = false ∧
    rowsOK (integral_affine_offset_long_B.headD []).length integral_affine_offset_long_cert.linear integral_affine_offset_long_cert.offset integral_affine_offset_long_A integral_affine_offset_long_B integral_affine_offset_long_c = true := by decide
#guard integral_affine_offset_long_cert.check integral_affine_offset_long_A integral_affine_offset_long_B integral_affine_offset_long_c = false

/-- NEGATIVE CONTROL `linear_row_long`: `W[0]` with an extra trailing 0; only the row-width test fails.
shapeOK = false, rowsOK = true (checked in Python and below). -/
def integral_affine_linear_row_long_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_linear_row_long_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_linear_row_long_c : List Int := [5, (-3)]
def integral_affine_linear_row_long_cert : AffineCert := { linear := [[(-1), (-9), 0], [2, 4]], offset := [11, (-3)] }
theorem integral_affine_linear_row_long_rejected : integral_affine_linear_row_long_cert.check integral_affine_linear_row_long_A integral_affine_linear_row_long_B integral_affine_linear_row_long_c = false := by decide
theorem integral_affine_linear_row_long_halves :
    shapeOK integral_affine_linear_row_long_A integral_affine_linear_row_long_B integral_affine_linear_row_long_c integral_affine_linear_row_long_cert = false ∧
    rowsOK (integral_affine_linear_row_long_B.headD []).length integral_affine_linear_row_long_cert.linear integral_affine_linear_row_long_cert.offset integral_affine_linear_row_long_A integral_affine_linear_row_long_B integral_affine_linear_row_long_c = true := by decide
#guard integral_affine_linear_row_long_cert.check integral_affine_linear_row_long_A integral_affine_linear_row_long_B integral_affine_linear_row_long_c = false

/-- NEGATIVE CONTROL `linear_extra_row`: `W` with an extra zero row; only the row-count test fails.
shapeOK = false, rowsOK = true (checked in Python and below). -/
def integral_affine_linear_extra_row_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_linear_extra_row_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_linear_extra_row_c : List Int := [5, (-3)]
def integral_affine_linear_extra_row_cert : AffineCert := { linear := [[(-1), (-9)], [2, 4], [0, 0]], offset := [11, (-3)] }
theorem integral_affine_linear_extra_row_rejected : integral_affine_linear_extra_row_cert.check integral_affine_linear_extra_row_A integral_affine_linear_extra_row_B integral_affine_linear_extra_row_c = false := by decide
theorem integral_affine_linear_extra_row_halves :
    shapeOK integral_affine_linear_extra_row_A integral_affine_linear_extra_row_B integral_affine_linear_extra_row_c integral_affine_linear_extra_row_cert = false ∧
    rowsOK (integral_affine_linear_extra_row_B.headD []).length integral_affine_linear_extra_row_cert.linear integral_affine_linear_extra_row_cert.offset integral_affine_linear_extra_row_A integral_affine_linear_extra_row_B integral_affine_linear_extra_row_c = true := by decide
#guard integral_affine_linear_extra_row_cert.check integral_affine_linear_extra_row_A integral_affine_linear_extra_row_B integral_affine_linear_extra_row_c = false

/-- NEGATIVE CONTROL `c_extra`: `c` with an extra entry; the rows of `A`, `B`, `c` no longer run out together.
shapeOK = false, rowsOK = false (checked in Python and below). -/
def integral_affine_c_extra_A : List (List Int) := [[1, 2], [0, 1]]
def integral_affine_c_extra_B : List (List Int) := [[3, (-1)], [2, 4]]
def integral_affine_c_extra_c : List Int := [5, (-3), 0]
def integral_affine_c_extra_cert : AffineCert := { linear := [[(-1), (-9)], [2, 4]], offset := [11, (-3)] }
theorem integral_affine_c_extra_rejected : integral_affine_c_extra_cert.check integral_affine_c_extra_A integral_affine_c_extra_B integral_affine_c_extra_c = false := by decide
theorem integral_affine_c_extra_halves :
    shapeOK integral_affine_c_extra_A integral_affine_c_extra_B integral_affine_c_extra_c integral_affine_c_extra_cert = false ∧
    rowsOK (integral_affine_c_extra_B.headD []).length integral_affine_c_extra_cert.linear integral_affine_c_extra_cert.offset integral_affine_c_extra_A integral_affine_c_extra_B integral_affine_c_extra_c = false := by decide
#guard integral_affine_c_extra_cert.check integral_affine_c_extra_A integral_affine_c_extra_B integral_affine_c_extra_c = false

/-! ### Integrality

`A = [[2]]`, `B = [[2]]`, `c = [1]`. Over the rationals `W = [[1]]`, `d = [1/2]`
is a witness, and the prototype accepts it when `require_integral` is False and
rejects it when True (the exporter checks both). Here that rejection is a
theorem about ALL certificates: none passes, because `2 * w = 2 * x + 1` has no
integer solution at `x = 0`.
-/

def integrality_A : List (List Int) := [[2]]
def integrality_B : List (List Int) := [[2]]
def integrality_c : List Int := [1]

theorem integrality_no_certificate (w : AffineCert) :
    w.check integrality_A integrality_B integrality_c = false := by
  cases h : w.check integrality_A integrality_B integrality_c with
  | false => rfl
  | true =>
    have hs := AffineCert.sound _ _ _ w h []
    simp only [integrality_A, integrality_B, integrality_c, AffineCert.apply,
      mulVec_cons, mulVec_nil, dot_nil_right, vadd_cons_cons, vadd_nil_left] at hs
    revert hs
    generalize vadd (mulVec w.linear []) w.offset = v
    cases v with
    | nil => intro hs; exact absurd (List.cons.inj hs).1 (by decide)
    | cons v vs =>
      intro hs
      have h1 := (List.cons.inj hs).1
      simp only [dot_cons_cons, dot_nil_left, Int.add_zero] at h1
      omega

#print axioms integral_affine_checks
#print axioms integral_affine_sound
#print axioms integral_affine_concrete
#print axioms integral_affine_exists
#print axioms integral_affine_mutation_offset0_rejected
#print axioms integral_affine_linear_entry_rejected
#print axioms integral_affine_offset_long_rejected
#print axioms integral_affine_linear_row_long_rejected
#print axioms integral_affine_linear_extra_row_rejected
#print axioms integral_affine_c_extra_rejected
#print axioms integrality_no_certificate

end Forge.Checker.AffineCorpus
