import Forge.Checker.Cone
/-
  GENERATED by tools/export_lean_cone.py from the prototype's certificate
  bundle. Do not edit by hand; regenerate.

  Every certificate below was produced by the Python search in
  prototype/forge/cone.py and prototype/forge/quadratic.py, over the rationals.
  The exporter cleared denominators, re-checked the resulting integer identity
  in Python, and emitted it here. The Lean kernel then checks it again by
  reduction, with no appeal to the compiler and no `native_decide`.

  This file is the loop the project is named for, closed once: a certificate a
  search produced, checked by Lean, with a proof that checking it establishes
  the mathematical claim.
-/
/- The `_concrete` proofs below are generated uniformly, so their `simp` sets
   mention lemmas that some of them do not need. Disabling the linter is
   preferable to emitting a different proof script per certificate. -/
set_option linter.unusedSimpArgs false

namespace Forge.Checker

/-! ### `hidden_quadratic` --- Quadratic SOS, 2 variables

The prototype's certificate is over the rationals. `hidden_quadratic_target` is
`7 * p`, the least positive integer multiple of the original
`p`. Since 7 > 0, the target is nonnegative exactly where `p` is.
-/

def hidden_quadratic_target : Poly := [([0, 0], 147), ([0, 1], (-168)), ([0, 2], 99), ([1, 0], (-126)), ([1, 1], (-26)), ([2, 0], 78)]

def hidden_quadratic_ineqs : List Poly := []

def hidden_quadratic_eqs : List Poly := []

def hidden_quadratic_cert : Cert where
  scale := 51
  squares := [
    { weight := 153, powers := [], poly := [([0, 0], 7), ([0, 1], (-4)), ([1, 0], (-3))] },
    { weight := 1, powers := [], poly := [([0, 1], (-49)), ([1, 0], 51)] },
    { weight := 200, powers := [], poly := [([0, 1], 1)] } ]
  multipliers := []

/-- The checker accepts. `decide` elaborates the `Bool` and the
kernel replays the reduction, so this rests on the kernel alone. -/
theorem hidden_quadratic_checks :
    hidden_quadratic_cert.check hidden_quadratic_target hidden_quadratic_ineqs hidden_quadratic_eqs = true := by decide

/-- Nonnegativity at every assignment satisfying the constraints.
Follows from the check by `Cert.sound`; no arithmetic is repeated
here and no property of the search is assumed. -/
theorem hidden_quadratic_nonneg (x : Env)
    : 0 ≤ eval x hidden_quadratic_target :=
  hidden_quadratic_cert.sound _ _ _ hidden_quadratic_checks x (by simp [hidden_quadratic_ineqs]) (by simp [hidden_quadratic_eqs])

/-- The same fact as `hidden_quadratic_nonneg`, stated in ordinary arithmetic.
This is the form a goal actually arrives in; the encoding above is
an implementation detail of the checker, not something to state. -/
theorem hidden_quadratic_concrete (x0 x1 : Int)
    : 0 ≤ 147 + (-168) * x1 + 99 * x1^2 + (-126) * x0 + (-26) * (x0 * x1) + 78 * x0^2 := by
  have h := hidden_quadratic_nonneg (fun i => if i = 0 then x0 else if i = 1 then x1 else 0) 
  simp [hidden_quadratic_target, eval, monoEval, monoEvalFrom, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `equality_constrained` --- Finite cone LP, 2 variables

The prototype's certificate is over the rationals. `equality_constrained_target` is
`2 * p`, the least positive integer multiple of the original
`p`. Since 2 > 0, the target is nonnegative exactly where `p` is.

The constraints are cleared the same way and by positive
multipliers, so the hypotheses below say exactly what the
original constraints say.
-/

def equality_constrained_target : Poly := [([0, 0], (-1)), ([0, 2], 2), ([2, 0], 2)]

def equality_constrained_ineqs : List Poly := []

def equality_constrained_eqs : List Poly := [[([0, 0], (-1)), ([0, 1], 1), ([1, 0], 1)]]

def equality_constrained_cert : Cert where
  scale := 1
  squares := [
    { weight := 1, powers := [], poly := [([0, 1], 1), ([1, 0], (-1))] } ]
  multipliers := [[([0, 0], 1), ([0, 1], 1), ([1, 0], 1)]]

/-- The checker accepts. `decide` elaborates the `Bool` and the
kernel replays the reduction, so this rests on the kernel alone. -/
theorem equality_constrained_checks :
    equality_constrained_cert.check equality_constrained_target equality_constrained_ineqs equality_constrained_eqs = true := by decide

/-- Nonnegativity at every assignment satisfying the constraints.
Follows from the check by `Cert.sound`; no arithmetic is repeated
here and no property of the search is assumed. -/
theorem equality_constrained_nonneg (x : Env)
    (hz : ∀ f ∈ equality_constrained_eqs, eval x f = 0)
    : 0 ≤ eval x equality_constrained_target :=
  equality_constrained_cert.sound _ _ _ equality_constrained_checks x (by simp [equality_constrained_ineqs]) hz

/-- The same fact as `equality_constrained_nonneg`, stated in ordinary arithmetic.
This is the form a goal actually arrives in; the encoding above is
an implementation detail of the checker, not something to state. -/
theorem equality_constrained_concrete (x0 x1 : Int)
    (hf0 : (-1) + 1 * x1 + 1 * x0 = 0)
    : 0 ≤ (-1) + 2 * x1^2 + 2 * x0^2 := by
  have h := equality_constrained_nonneg (fun i => if i = 0 then x0 else if i = 1 then x1 else 0) (by
    intro f hf
    simp [equality_constrained_eqs] at hf
    subst hf
    simp [eval, monoEval, monoEvalFrom, Int.pow_one, Int.pow_zero]
    omega)
  simp [equality_constrained_target, eval, monoEval, monoEvalFrom, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `guard_product` --- Finite cone LP, 2 variables

The prototype's certificate is over the rationals. `guard_product_target` is
the original `p`, whose coefficients were already integers.

The constraints are cleared the same way and by positive
multipliers, so the hypotheses below say exactly what the
original constraints say.
-/

def guard_product_target : Poly := [([1, 1], 1)]

def guard_product_ineqs : List Poly := [[([1, 0], 1)], [([0, 1], 1)]]

def guard_product_eqs : List Poly := []

def guard_product_cert : Cert where
  scale := 1
  squares := [
    { weight := 1, powers := [1, 1], poly := [([0, 0], 1)] } ]
  multipliers := []

/-- The checker accepts. `decide` elaborates the `Bool` and the
kernel replays the reduction, so this rests on the kernel alone. -/
theorem guard_product_checks :
    guard_product_cert.check guard_product_target guard_product_ineqs guard_product_eqs = true := by decide

/-- Nonnegativity at every assignment satisfying the constraints.
Follows from the check by `Cert.sound`; no arithmetic is repeated
here and no property of the search is assumed. -/
theorem guard_product_nonneg (x : Env)
    (hg : ∀ g ∈ guard_product_ineqs, 0 ≤ eval x g)
    : 0 ≤ eval x guard_product_target :=
  guard_product_cert.sound _ _ _ guard_product_checks x hg (by simp [guard_product_eqs])

/-- The same fact as `guard_product_nonneg`, stated in ordinary arithmetic.
This is the form a goal actually arrives in; the encoding above is
an implementation detail of the checker, not something to state. -/
theorem guard_product_concrete (x0 x1 : Int)
    (hg0 : 0 ≤ 1 * x0)
    (hg1 : 0 ≤ 1 * x1)
    : 0 ≤ 1 * (x0 * x1) := by
  have h := guard_product_nonneg (fun i => if i = 0 then x0 else if i = 1 then x1 else 0) (by
    intro g hg
    simp [guard_product_ineqs] at hg
    rcases hg with rfl | rfl <;>
      simp [eval, monoEval, monoEvalFrom, Int.pow_one, Int.pow_zero] <;> omega)
  simp [guard_product_target, eval, monoEval, monoEvalFrom, Int.pow_one, Int.pow_zero] at h
  omega
end Forge.Checker
