import Forge.Checker.Farkas
/-
  GENERATED by tools/export_lean_farkas.py from the prototype's certificate
  bundle (family "Farkas refutation"). Do not edit by hand; regenerate.

  Each certificate below was accepted by the prototype's `check_farkas` and by an
  integer re-implementation of `FarkasCert.check` in the exporter, and is
  accepted here again by the Lean kernel via `decide`. No `native_decide`.

  `_infeasible` is `FarkasCert.sound` applied to `_checks`: no decision
  procedure is involved. `_concrete` restates it in ordinary arithmetic. Each
  row lemma `_row_i` uses `omega` to identify ONE hypothesis with its unfolded
  constraint, and sees only that hypothesis; the refutation itself comes from the
  certificate. (These systems are small enough that `omega` could refute them
  outright; the point here is that the prototype's certificate is what the
  kernel checks.)

  Negative controls: the bundle's two mutations, plus controls that each break
  named conjuncts of the checker, as recorded in results/lean-farkas-corpus.json.
-/

namespace Forge.Checker.FarkasCorpus
open Forge.Checker.Lin Forge.Checker.Farkas

/-! ### `strict_cycle` --- 3 constraints in 3 variables -/

def strict_cycle_rows : List Constraint := [⟨[1, (-1), 0], (-1)⟩, ⟨[0, 1, (-1)], (-1)⟩, ⟨[(-1), 0, 1], (-1)⟩]
def strict_cycle_cert : FarkasCert := ⟨[1, 1, 1]⟩

/-- The checker accepts, by kernel reduction. -/
theorem strict_cycle_checks : strict_cycle_cert.check 3 strict_cycle_rows = true := by decide

/-- No integer point satisfies every row. -/
theorem strict_cycle_infeasible (x : List Int) : ¬ ∀ r ∈ strict_cycle_rows, r.Holds x :=
  FarkasCert.sound 3 strict_cycle_rows strict_cycle_cert strict_cycle_checks x

theorem strict_cycle_row_0 (x0 x1 x2 : Int) (h : x0 + -x1 ≤ (-1)) :
    Constraint.Holds [x0, x1, x2] ⟨[1, (-1), 0], (-1)⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem strict_cycle_row_1 (x0 x1 x2 : Int) (h : x1 + -x2 ≤ (-1)) :
    Constraint.Holds [x0, x1, x2] ⟨[0, 1, (-1)], (-1)⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem strict_cycle_row_2 (x0 x1 x2 : Int) (h : -x0 + x2 ≤ (-1)) :
    Constraint.Holds [x0, x1, x2] ⟨[(-1), 0, 1], (-1)⟩ := by
  simp only [Constraint.Holds, dot]
  omega

/-- The same fact in ordinary arithmetic. -/
theorem strict_cycle_concrete (x0 x1 x2 : Int) :
    ¬ (x0 + -x1 ≤ (-1) ∧
       x1 + -x2 ≤ (-1) ∧
       -x0 + x2 ≤ (-1)) := by
  intro ⟨h0, h1, h2⟩
  apply strict_cycle_infeasible [x0, x1, x2]
  intro r hr
  simp only [strict_cycle_rows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl
  · exact strict_cycle_row_0 x0 x1 x2 h0
  · exact strict_cycle_row_1 x0 x1 x2 h1
  · exact strict_cycle_row_2 x0 x1 x2 h2

/-- NEGATIVE CONTROL `mutation_mult0`: the bundle's mutation `multipliers[0] + 1`. Failing conjuncts: combination. -/
def strict_cycle_mutation_mult0_rows : List Constraint := [⟨[1, (-1), 0], (-1)⟩, ⟨[0, 1, (-1)], (-1)⟩, ⟨[(-1), 0, 1], (-1)⟩]
def strict_cycle_mutation_mult0_cert : FarkasCert := ⟨[2, 1, 1]⟩
theorem strict_cycle_mutation_mult0_rejected : strict_cycle_mutation_mult0_cert.check 3 strict_cycle_mutation_mult0_rows = false := by decide

/-- NEGATIVE CONTROL `mutation_bounds`: the bundle's mutation, every bound + 1000. Failing conjuncts: strictness. -/
def strict_cycle_mutation_bounds_rows : List Constraint := [⟨[1, (-1), 0], 999⟩, ⟨[0, 1, (-1)], 999⟩, ⟨[(-1), 0, 1], 999⟩]
def strict_cycle_mutation_bounds_cert : FarkasCert := ⟨[1, 1, 1]⟩
theorem strict_cycle_mutation_bounds_rejected : strict_cycle_mutation_bounds_cert.check 3 strict_cycle_mutation_bounds_rows = false := by decide

/-- NEGATIVE CONTROL `zero_multipliers`: all multipliers 0; the combination is `0 ≤ 0`. Failing conjuncts: strictness. -/
def strict_cycle_zero_multipliers_rows : List Constraint := [⟨[1, (-1), 0], (-1)⟩, ⟨[0, 1, (-1)], (-1)⟩, ⟨[(-1), 0, 1], (-1)⟩]
def strict_cycle_zero_multipliers_cert : FarkasCert := ⟨[0, 0, 0]⟩
theorem strict_cycle_zero_multipliers_rejected : strict_cycle_zero_multipliers_cert.check 3 strict_cycle_zero_multipliers_rows = false := by decide

/-- NEGATIVE CONTROL `extra_multiplier`: one more multiplier than rows. Failing conjuncts: count. -/
def strict_cycle_extra_multiplier_rows : List Constraint := [⟨[1, (-1), 0], (-1)⟩, ⟨[0, 1, (-1)], (-1)⟩, ⟨[(-1), 0, 1], (-1)⟩]
def strict_cycle_extra_multiplier_cert : FarkasCert := ⟨[1, 1, 1, 0]⟩
theorem strict_cycle_extra_multiplier_rejected : strict_cycle_extra_multiplier_cert.check 3 strict_cycle_extra_multiplier_rows = false := by decide

/-- NEGATIVE CONTROL `negated`: every multiplier negated. Failing conjuncts: sign, strictness. -/
def strict_cycle_negated_rows : List Constraint := [⟨[1, (-1), 0], (-1)⟩, ⟨[0, 1, (-1)], (-1)⟩, ⟨[(-1), 0, 1], (-1)⟩]
def strict_cycle_negated_cert : FarkasCert := ⟨[(-1), (-1), (-1)]⟩
theorem strict_cycle_negated_rejected : strict_cycle_negated_cert.check 3 strict_cycle_negated_rows = false := by decide

/-! ### `resource_overrun` --- 3 constraints in 2 variables -/

def resource_overrun_rows : List Constraint := [⟨[2, 3], 12⟩, ⟨[(-1), 0], (-4)⟩, ⟨[0, (-1)], (-2)⟩]
def resource_overrun_cert : FarkasCert := ⟨[1, 2, 3]⟩

/-- The checker accepts, by kernel reduction. -/
theorem resource_overrun_checks : resource_overrun_cert.check 2 resource_overrun_rows = true := by decide

/-- No integer point satisfies every row. -/
theorem resource_overrun_infeasible (x : List Int) : ¬ ∀ r ∈ resource_overrun_rows, r.Holds x :=
  FarkasCert.sound 2 resource_overrun_rows resource_overrun_cert resource_overrun_checks x

theorem resource_overrun_row_0 (x0 x1 : Int) (h : 2 * x0 + 3 * x1 ≤ 12) :
    Constraint.Holds [x0, x1] ⟨[2, 3], 12⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem resource_overrun_row_1 (x0 x1 : Int) (h : -x0 ≤ (-4)) :
    Constraint.Holds [x0, x1] ⟨[(-1), 0], (-4)⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem resource_overrun_row_2 (x0 x1 : Int) (h : -x1 ≤ (-2)) :
    Constraint.Holds [x0, x1] ⟨[0, (-1)], (-2)⟩ := by
  simp only [Constraint.Holds, dot]
  omega

/-- The same fact in ordinary arithmetic. -/
theorem resource_overrun_concrete (x0 x1 : Int) :
    ¬ (2 * x0 + 3 * x1 ≤ 12 ∧
       -x0 ≤ (-4) ∧
       -x1 ≤ (-2)) := by
  intro ⟨h0, h1, h2⟩
  apply resource_overrun_infeasible [x0, x1]
  intro r hr
  simp only [resource_overrun_rows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl
  · exact resource_overrun_row_0 x0 x1 h0
  · exact resource_overrun_row_1 x0 x1 h1
  · exact resource_overrun_row_2 x0 x1 h2

/-- NEGATIVE CONTROL `mutation_mult0`: the bundle's mutation `multipliers[0] + 1`. Failing conjuncts: combination, strictness. -/
def resource_overrun_mutation_mult0_rows : List Constraint := [⟨[2, 3], 12⟩, ⟨[(-1), 0], (-4)⟩, ⟨[0, (-1)], (-2)⟩]
def resource_overrun_mutation_mult0_cert : FarkasCert := ⟨[2, 2, 3]⟩
theorem resource_overrun_mutation_mult0_rejected : resource_overrun_mutation_mult0_cert.check 2 resource_overrun_mutation_mult0_rows = false := by decide

/-- NEGATIVE CONTROL `mutation_bounds`: the bundle's mutation, every bound + 1000. Failing conjuncts: strictness. -/
def resource_overrun_mutation_bounds_rows : List Constraint := [⟨[2, 3], 1012⟩, ⟨[(-1), 0], 996⟩, ⟨[0, (-1)], 998⟩]
def resource_overrun_mutation_bounds_cert : FarkasCert := ⟨[1, 2, 3]⟩
theorem resource_overrun_mutation_bounds_rejected : resource_overrun_mutation_bounds_cert.check 2 resource_overrun_mutation_bounds_rows = false := by decide

/-- NEGATIVE CONTROL `zero_multipliers`: all multipliers 0; the combination is `0 ≤ 0`. Failing conjuncts: strictness. -/
def resource_overrun_zero_multipliers_rows : List Constraint := [⟨[2, 3], 12⟩, ⟨[(-1), 0], (-4)⟩, ⟨[0, (-1)], (-2)⟩]
def resource_overrun_zero_multipliers_cert : FarkasCert := ⟨[0, 0, 0]⟩
theorem resource_overrun_zero_multipliers_rejected : resource_overrun_zero_multipliers_cert.check 2 resource_overrun_zero_multipliers_rows = false := by decide

/-- NEGATIVE CONTROL `extra_multiplier`: one more multiplier than rows. Failing conjuncts: count. -/
def resource_overrun_extra_multiplier_rows : List Constraint := [⟨[2, 3], 12⟩, ⟨[(-1), 0], (-4)⟩, ⟨[0, (-1)], (-2)⟩]
def resource_overrun_extra_multiplier_cert : FarkasCert := ⟨[1, 2, 3, 0]⟩
theorem resource_overrun_extra_multiplier_rejected : resource_overrun_extra_multiplier_cert.check 2 resource_overrun_extra_multiplier_rows = false := by decide

/-- NEGATIVE CONTROL `negated`: every multiplier negated. Failing conjuncts: sign, strictness. -/
def resource_overrun_negated_rows : List Constraint := [⟨[2, 3], 12⟩, ⟨[(-1), 0], (-4)⟩, ⟨[0, (-1)], (-2)⟩]
def resource_overrun_negated_cert : FarkasCert := ⟨[(-1), (-2), (-3)]⟩
theorem resource_overrun_negated_rejected : resource_overrun_negated_cert.check 2 resource_overrun_negated_rows = false := by decide

/-! ### `mixed_three_var` --- 4 constraints in 3 variables -/

def mixed_three_var_rows : List Constraint := [⟨[3, (-2), 0], 1⟩, ⟨[0, 5, (-4)], 2⟩, ⟨[(-1), 0, 2], (-6)⟩, ⟨[0, (-1), (-1)], 0⟩]
def mixed_three_var_cert : FarkasCert := ⟨[9, 8, 27, 22]⟩

/-- The checker accepts, by kernel reduction. -/
theorem mixed_three_var_checks : mixed_three_var_cert.check 3 mixed_three_var_rows = true := by decide

/-- No integer point satisfies every row. -/
theorem mixed_three_var_infeasible (x : List Int) : ¬ ∀ r ∈ mixed_three_var_rows, r.Holds x :=
  FarkasCert.sound 3 mixed_three_var_rows mixed_three_var_cert mixed_three_var_checks x

theorem mixed_three_var_row_0 (x0 x1 x2 : Int) (h : 3 * x0 + (-2) * x1 ≤ 1) :
    Constraint.Holds [x0, x1, x2] ⟨[3, (-2), 0], 1⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem mixed_three_var_row_1 (x0 x1 x2 : Int) (h : 5 * x1 + (-4) * x2 ≤ 2) :
    Constraint.Holds [x0, x1, x2] ⟨[0, 5, (-4)], 2⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem mixed_three_var_row_2 (x0 x1 x2 : Int) (h : -x0 + 2 * x2 ≤ (-6)) :
    Constraint.Holds [x0, x1, x2] ⟨[(-1), 0, 2], (-6)⟩ := by
  simp only [Constraint.Holds, dot]
  omega

theorem mixed_three_var_row_3 (x0 x1 x2 : Int) (h : -x1 + -x2 ≤ 0) :
    Constraint.Holds [x0, x1, x2] ⟨[0, (-1), (-1)], 0⟩ := by
  simp only [Constraint.Holds, dot]
  omega

/-- The same fact in ordinary arithmetic. -/
theorem mixed_three_var_concrete (x0 x1 x2 : Int) :
    ¬ (3 * x0 + (-2) * x1 ≤ 1 ∧
       5 * x1 + (-4) * x2 ≤ 2 ∧
       -x0 + 2 * x2 ≤ (-6) ∧
       -x1 + -x2 ≤ 0) := by
  intro ⟨h0, h1, h2, h3⟩
  apply mixed_three_var_infeasible [x0, x1, x2]
  intro r hr
  simp only [mixed_three_var_rows, List.mem_cons, List.not_mem_nil, or_false] at hr
  rcases hr with rfl | rfl | rfl | rfl
  · exact mixed_three_var_row_0 x0 x1 x2 h0
  · exact mixed_three_var_row_1 x0 x1 x2 h1
  · exact mixed_three_var_row_2 x0 x1 x2 h2
  · exact mixed_three_var_row_3 x0 x1 x2 h3

/-- NEGATIVE CONTROL `mutation_mult0`: the bundle's mutation `multipliers[0] + 1`. Failing conjuncts: combination. -/
def mixed_three_var_mutation_mult0_rows : List Constraint := [⟨[3, (-2), 0], 1⟩, ⟨[0, 5, (-4)], 2⟩, ⟨[(-1), 0, 2], (-6)⟩, ⟨[0, (-1), (-1)], 0⟩]
def mixed_three_var_mutation_mult0_cert : FarkasCert := ⟨[10, 8, 27, 22]⟩
theorem mixed_three_var_mutation_mult0_rejected : mixed_three_var_mutation_mult0_cert.check 3 mixed_three_var_mutation_mult0_rows = false := by decide

/-- NEGATIVE CONTROL `mutation_bounds`: the bundle's mutation, every bound + 1000. Failing conjuncts: strictness. -/
def mixed_three_var_mutation_bounds_rows : List Constraint := [⟨[3, (-2), 0], 1001⟩, ⟨[0, 5, (-4)], 1002⟩, ⟨[(-1), 0, 2], 994⟩, ⟨[0, (-1), (-1)], 1000⟩]
def mixed_three_var_mutation_bounds_cert : FarkasCert := ⟨[9, 8, 27, 22]⟩
theorem mixed_three_var_mutation_bounds_rejected : mixed_three_var_mutation_bounds_cert.check 3 mixed_three_var_mutation_bounds_rows = false := by decide

/-- NEGATIVE CONTROL `zero_multipliers`: all multipliers 0; the combination is `0 ≤ 0`. Failing conjuncts: strictness. -/
def mixed_three_var_zero_multipliers_rows : List Constraint := [⟨[3, (-2), 0], 1⟩, ⟨[0, 5, (-4)], 2⟩, ⟨[(-1), 0, 2], (-6)⟩, ⟨[0, (-1), (-1)], 0⟩]
def mixed_three_var_zero_multipliers_cert : FarkasCert := ⟨[0, 0, 0, 0]⟩
theorem mixed_three_var_zero_multipliers_rejected : mixed_three_var_zero_multipliers_cert.check 3 mixed_three_var_zero_multipliers_rows = false := by decide

/-- NEGATIVE CONTROL `extra_multiplier`: one more multiplier than rows. Failing conjuncts: count. -/
def mixed_three_var_extra_multiplier_rows : List Constraint := [⟨[3, (-2), 0], 1⟩, ⟨[0, 5, (-4)], 2⟩, ⟨[(-1), 0, 2], (-6)⟩, ⟨[0, (-1), (-1)], 0⟩]
def mixed_three_var_extra_multiplier_cert : FarkasCert := ⟨[9, 8, 27, 22, 0]⟩
theorem mixed_three_var_extra_multiplier_rejected : mixed_three_var_extra_multiplier_cert.check 3 mixed_three_var_extra_multiplier_rows = false := by decide

/-- NEGATIVE CONTROL `negated`: every multiplier negated. Failing conjuncts: sign, strictness. -/
def mixed_three_var_negated_rows : List Constraint := [⟨[3, (-2), 0], 1⟩, ⟨[0, 5, (-4)], 2⟩, ⟨[(-1), 0, 2], (-6)⟩, ⟨[0, (-1), (-1)], 0⟩]
def mixed_three_var_negated_cert : FarkasCert := ⟨[(-9), (-8), (-27), (-22)]⟩
theorem mixed_three_var_negated_rejected : mixed_three_var_negated_cert.check 3 mixed_three_var_negated_rows = false := by decide
#print axioms strict_cycle_checks
#print axioms strict_cycle_infeasible
#print axioms strict_cycle_concrete
#print axioms strict_cycle_mutation_mult0_rejected
#print axioms strict_cycle_mutation_bounds_rejected
#print axioms strict_cycle_zero_multipliers_rejected
#print axioms strict_cycle_extra_multiplier_rejected
#print axioms strict_cycle_negated_rejected
#print axioms resource_overrun_checks
#print axioms resource_overrun_infeasible
#print axioms resource_overrun_concrete
#print axioms resource_overrun_mutation_mult0_rejected
#print axioms resource_overrun_mutation_bounds_rejected
#print axioms resource_overrun_zero_multipliers_rejected
#print axioms resource_overrun_extra_multiplier_rejected
#print axioms resource_overrun_negated_rejected
#print axioms mixed_three_var_checks
#print axioms mixed_three_var_infeasible
#print axioms mixed_three_var_concrete
#print axioms mixed_three_var_mutation_mult0_rejected
#print axioms mixed_three_var_mutation_bounds_rejected
#print axioms mixed_three_var_zero_multipliers_rejected
#print axioms mixed_three_var_extra_multiplier_rejected
#print axioms mixed_three_var_negated_rejected

end Forge.Checker.FarkasCorpus
