import Forge.Checker.Recurrence
/-
  GENERATED by tools/export_lean_recurrence.py from the prototype's certificate
  bundle (prototype/results/certificates.json). Do not edit by hand; regenerate.

  Families: "Polynomial recurrence" (every record) and "Conserved invariant"
  (every record). Each certificate was re-checked in Python by the prototype's
  own checker over the rationals and by a mirror of the Lean checker over the
  cleared integers, then checked here by kernel reduction (`decide`).
  No `native_decide`.

  Every `_concrete` theorem is derived FROM the certificate's soundness theorem.
  The `_seq_eq` / `_run_reachable` lemmas only identify the encoded sequence or
  state space with an ordinary core-recursive definition; they contain no
  arithmetic about the closed form or the invariant.
-/
set_option linter.unusedSimpArgs false

namespace Forge.Checker

/-- A pair of integers as a state. -/
def pairEnv (p : Int × Int) : Env := fun i => if i = 0 then p.1 else if i = 1 then p.2 else 0

/-! ### `power_sum_0` --- Polynomial recurrence, index plus 0 parameter(s)

Prototype checker (`check_recurrence`) accepts: true.
The prototype's closed form is rational. `power_sum_0_cert.formula` is
`1` times it. The Lean statement is
`1 * seq = formula`; since 1 > 0 this says exactly that the
sequence equals the prototype's closed form.
-/

def power_sum_0_step : Poly := [([0], 1)]

def power_sum_0_initial : Poly := []

def power_sum_0_cert : RecCert where
  scale := 1
  formula := [([1], 1)]

/-- The checker accepts, by kernel reduction. -/
theorem power_sum_0_checks : power_sum_0_cert.check power_sum_0_step power_sum_0_initial = true := by decide

/-- Soundness, instantiated: every index, every parameter assignment. -/
theorem power_sum_0_closed_form (a : Env) (n : Nat) :
    power_sum_0_cert.scale * recSeq power_sum_0_step power_sum_0_initial a n = eval (setVar0 a n) power_sum_0_cert.formula :=
  power_sum_0_cert.sound _ _ power_sum_0_checks a n

/-- The sequence, written as ordinary core recursion:
`seq 0 = initial`, `seq (n+1) = seq n + step n`. -/
def power_sum_0_seq : Nat → Int
  | 0 => 0
  | n + 1 => power_sum_0_seq n + (1)

/-- The encoded sequence is the one written above. This relates two
definitions; it proves nothing about the closed form. -/
theorem power_sum_0_seq_eq : ∀ n : Nat,
    recSeq power_sum_0_step power_sum_0_initial (fun _ => 0) n = power_sum_0_seq n
  | 0 => by simp [recSeq, power_sum_0_seq, power_sum_0_initial, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
  | n + 1 => by
    simp only [recSeq, power_sum_0_seq, power_sum_0_seq_eq n]
    simp [power_sum_0_step, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega

/-- **The claim in ordinary arithmetic**, derived from the certificate
via `power_sum_0_closed_form`; no induction on the closed form is done here. -/
theorem power_sum_0_concrete (n : Nat) :
    1 * power_sum_0_seq n = (n : Int) := by
  have h := power_sum_0_closed_form (fun _ => 0) n
  rw [power_sum_0_seq_eq] at h
  simp [power_sum_0_cert, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `power_sum_1` --- Polynomial recurrence, index plus 0 parameter(s)

Prototype checker (`check_recurrence`) accepts: true.
The prototype's closed form is rational. `power_sum_1_cert.formula` is
`2` times it. The Lean statement is
`2 * seq = formula`; since 2 > 0 this says exactly that the
sequence equals the prototype's closed form.
-/

def power_sum_1_step : Poly := [([1], 1)]

def power_sum_1_initial : Poly := []

def power_sum_1_cert : RecCert where
  scale := 2
  formula := [([1], (-1)), ([2], 1)]

/-- The checker accepts, by kernel reduction. -/
theorem power_sum_1_checks : power_sum_1_cert.check power_sum_1_step power_sum_1_initial = true := by decide

/-- Soundness, instantiated: every index, every parameter assignment. -/
theorem power_sum_1_closed_form (a : Env) (n : Nat) :
    power_sum_1_cert.scale * recSeq power_sum_1_step power_sum_1_initial a n = eval (setVar0 a n) power_sum_1_cert.formula :=
  power_sum_1_cert.sound _ _ power_sum_1_checks a n

/-- The sequence, written as ordinary core recursion:
`seq 0 = initial`, `seq (n+1) = seq n + step n`. -/
def power_sum_1_seq : Nat → Int
  | 0 => 0
  | n + 1 => power_sum_1_seq n + ((n : Int))

/-- The encoded sequence is the one written above. This relates two
definitions; it proves nothing about the closed form. -/
theorem power_sum_1_seq_eq : ∀ n : Nat,
    recSeq power_sum_1_step power_sum_1_initial (fun _ => 0) n = power_sum_1_seq n
  | 0 => by simp [recSeq, power_sum_1_seq, power_sum_1_initial, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
  | n + 1 => by
    simp only [recSeq, power_sum_1_seq, power_sum_1_seq_eq n]
    simp [power_sum_1_step, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega

/-- **The claim in ordinary arithmetic**, derived from the certificate
via `power_sum_1_closed_form`; no induction on the closed form is done here. -/
theorem power_sum_1_concrete (n : Nat) :
    2 * power_sum_1_seq n = -(n : Int) + (n : Int)^2 := by
  have h := power_sum_1_closed_form (fun _ => 0) n
  rw [power_sum_1_seq_eq] at h
  simp [power_sum_1_cert, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `power_sum_2` --- Polynomial recurrence, index plus 0 parameter(s)

Prototype checker (`check_recurrence`) accepts: true.
The prototype's closed form is rational. `power_sum_2_cert.formula` is
`6` times it. The Lean statement is
`6 * seq = formula`; since 6 > 0 this says exactly that the
sequence equals the prototype's closed form.
-/

def power_sum_2_step : Poly := [([2], 1)]

def power_sum_2_initial : Poly := []

def power_sum_2_cert : RecCert where
  scale := 6
  formula := [([1], 1), ([2], (-3)), ([3], 2)]

/-- The checker accepts, by kernel reduction. -/
theorem power_sum_2_checks : power_sum_2_cert.check power_sum_2_step power_sum_2_initial = true := by decide

/-- Soundness, instantiated: every index, every parameter assignment. -/
theorem power_sum_2_closed_form (a : Env) (n : Nat) :
    power_sum_2_cert.scale * recSeq power_sum_2_step power_sum_2_initial a n = eval (setVar0 a n) power_sum_2_cert.formula :=
  power_sum_2_cert.sound _ _ power_sum_2_checks a n

/-- The sequence, written as ordinary core recursion:
`seq 0 = initial`, `seq (n+1) = seq n + step n`. -/
def power_sum_2_seq : Nat → Int
  | 0 => 0
  | n + 1 => power_sum_2_seq n + ((n : Int)^2)

/-- The encoded sequence is the one written above. This relates two
definitions; it proves nothing about the closed form. -/
theorem power_sum_2_seq_eq : ∀ n : Nat,
    recSeq power_sum_2_step power_sum_2_initial (fun _ => 0) n = power_sum_2_seq n
  | 0 => by simp [recSeq, power_sum_2_seq, power_sum_2_initial, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
  | n + 1 => by
    simp only [recSeq, power_sum_2_seq, power_sum_2_seq_eq n]
    simp [power_sum_2_step, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega

/-- **The claim in ordinary arithmetic**, derived from the certificate
via `power_sum_2_closed_form`; no induction on the closed form is done here. -/
theorem power_sum_2_concrete (n : Nat) :
    6 * power_sum_2_seq n = (n : Int) - 3 * (n : Int)^2 + 2 * (n : Int)^3 := by
  have h := power_sum_2_closed_form (fun _ => 0) n
  rw [power_sum_2_seq_eq] at h
  simp [power_sum_2_cert, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `power_sum_3` --- Polynomial recurrence, index plus 0 parameter(s)

Prototype checker (`check_recurrence`) accepts: true.
The prototype's closed form is rational. `power_sum_3_cert.formula` is
`4` times it. The Lean statement is
`4 * seq = formula`; since 4 > 0 this says exactly that the
sequence equals the prototype's closed form.
-/

def power_sum_3_step : Poly := [([3], 1)]

def power_sum_3_initial : Poly := []

def power_sum_3_cert : RecCert where
  scale := 4
  formula := [([2], 1), ([3], (-2)), ([4], 1)]

/-- The checker accepts, by kernel reduction. -/
theorem power_sum_3_checks : power_sum_3_cert.check power_sum_3_step power_sum_3_initial = true := by decide

/-- Soundness, instantiated: every index, every parameter assignment. -/
theorem power_sum_3_closed_form (a : Env) (n : Nat) :
    power_sum_3_cert.scale * recSeq power_sum_3_step power_sum_3_initial a n = eval (setVar0 a n) power_sum_3_cert.formula :=
  power_sum_3_cert.sound _ _ power_sum_3_checks a n

/-- The sequence, written as ordinary core recursion:
`seq 0 = initial`, `seq (n+1) = seq n + step n`. -/
def power_sum_3_seq : Nat → Int
  | 0 => 0
  | n + 1 => power_sum_3_seq n + ((n : Int)^3)

/-- The encoded sequence is the one written above. This relates two
definitions; it proves nothing about the closed form. -/
theorem power_sum_3_seq_eq : ∀ n : Nat,
    recSeq power_sum_3_step power_sum_3_initial (fun _ => 0) n = power_sum_3_seq n
  | 0 => by simp [recSeq, power_sum_3_seq, power_sum_3_initial, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
  | n + 1 => by
    simp only [recSeq, power_sum_3_seq, power_sum_3_seq_eq n]
    simp [power_sum_3_step, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega

/-- **The claim in ordinary arithmetic**, derived from the certificate
via `power_sum_3_closed_form`; no induction on the closed form is done here. -/
theorem power_sum_3_concrete (n : Nat) :
    4 * power_sum_3_seq n = (n : Int)^2 - 2 * (n : Int)^3 + (n : Int)^4 := by
  have h := power_sum_3_closed_form (fun _ => 0) n
  rw [power_sum_3_seq_eq] at h
  simp [power_sum_3_cert, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `power_sum_4` --- Polynomial recurrence, index plus 0 parameter(s)

Prototype checker (`check_recurrence`) accepts: true.
The prototype's closed form is rational. `power_sum_4_cert.formula` is
`30` times it. The Lean statement is
`30 * seq = formula`; since 30 > 0 this says exactly that the
sequence equals the prototype's closed form.
-/

def power_sum_4_step : Poly := [([4], 1)]

def power_sum_4_initial : Poly := []

def power_sum_4_cert : RecCert where
  scale := 30
  formula := [([1], (-1)), ([3], 10), ([4], (-15)), ([5], 6)]

/-- The checker accepts, by kernel reduction. -/
theorem power_sum_4_checks : power_sum_4_cert.check power_sum_4_step power_sum_4_initial = true := by decide

/-- Soundness, instantiated: every index, every parameter assignment. -/
theorem power_sum_4_closed_form (a : Env) (n : Nat) :
    power_sum_4_cert.scale * recSeq power_sum_4_step power_sum_4_initial a n = eval (setVar0 a n) power_sum_4_cert.formula :=
  power_sum_4_cert.sound _ _ power_sum_4_checks a n

/-- The sequence, written as ordinary core recursion:
`seq 0 = initial`, `seq (n+1) = seq n + step n`. -/
def power_sum_4_seq : Nat → Int
  | 0 => 0
  | n + 1 => power_sum_4_seq n + ((n : Int)^4)

/-- The encoded sequence is the one written above. This relates two
definitions; it proves nothing about the closed form. -/
theorem power_sum_4_seq_eq : ∀ n : Nat,
    recSeq power_sum_4_step power_sum_4_initial (fun _ => 0) n = power_sum_4_seq n
  | 0 => by simp [recSeq, power_sum_4_seq, power_sum_4_initial, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
  | n + 1 => by
    simp only [recSeq, power_sum_4_seq, power_sum_4_seq_eq n]
    simp [power_sum_4_step, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega

/-- **The claim in ordinary arithmetic**, derived from the certificate
via `power_sum_4_closed_form`; no induction on the closed form is done here. -/
theorem power_sum_4_concrete (n : Nat) :
    30 * power_sum_4_seq n = -(n : Int) + 10 * (n : Int)^3 - 15 * (n : Int)^4 + 6 * (n : Int)^5 := by
  have h := power_sum_4_closed_form (fun _ => 0) n
  rw [power_sum_4_seq_eq] at h
  simp [power_sum_4_cert, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `param_linear_control` --- Polynomial recurrence, index plus 1 parameter(s)

Prototype checker (`check_recurrence`) accepts: true.
The prototype's closed form is rational. `param_linear_control_cert.formula` is
`1` times it. The Lean statement is
`1 * seq = formula`; since 1 > 0 this says exactly that the
sequence equals the prototype's closed form.
-/

def param_linear_control_step : Poly := [([0, 1], 1)]

def param_linear_control_initial : Poly := [([0, 1], 1)]

def param_linear_control_cert : RecCert where
  scale := 1
  formula := [([0, 1], 1), ([1, 1], 1)]

/-- The checker accepts, by kernel reduction. -/
theorem param_linear_control_checks : param_linear_control_cert.check param_linear_control_step param_linear_control_initial = true := by decide

/-- Soundness, instantiated: every index, every parameter assignment. -/
theorem param_linear_control_closed_form (a : Env) (n : Nat) :
    param_linear_control_cert.scale * recSeq param_linear_control_step param_linear_control_initial a n = eval (setVar0 a n) param_linear_control_cert.formula :=
  param_linear_control_cert.sound _ _ param_linear_control_checks a n

/-- The sequence, written as ordinary core recursion:
`seq 0 = initial`, `seq (n+1) = seq n + step n`. -/
def param_linear_control_seq (a1 : Int) : Nat → Int
  | 0 => a1
  | n + 1 => param_linear_control_seq a1 n + (a1)

/-- The encoded sequence is the one written above. This relates two
definitions; it proves nothing about the closed form. -/
theorem param_linear_control_seq_eq (a1 : Int) : ∀ n : Nat,
    recSeq param_linear_control_step param_linear_control_initial (fun i => if i = 1 then a1 else 0) n = param_linear_control_seq a1 n
  | 0 => by simp [recSeq, param_linear_control_seq, param_linear_control_initial, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
  | n + 1 => by
    simp only [recSeq, param_linear_control_seq, param_linear_control_seq_eq a1 n]
    simp [param_linear_control_step, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega

/-- **The claim in ordinary arithmetic**, derived from the certificate
via `param_linear_control_closed_form`; no induction on the closed form is done here. -/
theorem param_linear_control_concrete (n : Nat) (a1 : Int) :
    1 * param_linear_control_seq a1 n = a1 + ((n : Int) * a1) := by
  have h := param_linear_control_closed_form (fun i => if i = 1 then a1 else 0) n
  rw [param_linear_control_seq_eq] at h
  simp [param_linear_control_cert, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at h
  omega

/-! ### `cubic_accumulator` --- Conserved invariant, 2 state variables

Prototype checker (`check_invariant`) accepts: true.
`cubic_accumulator_cert.invariant` is `4` times the prototype's rational invariant;
since 4 > 0 it vanishes exactly where the rational one does. The
initial point and the transition map are integral and are not scaled.
-/

def cubic_accumulator_initial : List Int := [0, 0]

def cubic_accumulator_transition : List Poly :=
  [[([0, 0], 1), ([1, 0], 1)],
   [([0, 0], 1), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]]

def cubic_accumulator_cert : InvCert where
  scale := 4
  invariant := [([0, 1], 4), ([2, 0], (-1)), ([3, 0], (-2)), ([4, 0], (-1))]

/-- The checker accepts, by kernel reduction. -/
theorem cubic_accumulator_checks :
    cubic_accumulator_cert.check cubic_accumulator_initial cubic_accumulator_transition = true := by decide

/-- Soundness, instantiated: the invariant holds at EVERY reachable state. -/
theorem cubic_accumulator_invariant (s : Env)
    (hs : Reachable cubic_accumulator_transition (pointEnv cubic_accumulator_initial) s) :
    eval s cubic_accumulator_cert.invariant = 0 :=
  cubic_accumulator_cert.sound _ _ cubic_accumulator_checks s hs

/-- The loop, written as ordinary core recursion on a pair. -/
def cubic_accumulator_run : Nat → Int × Int
  | 0 => (0, 0)
  | k + 1 => (1 + (cubic_accumulator_run k).1,
      1 + (cubic_accumulator_run k).2 + 3 * (cubic_accumulator_run k).1 + 3 * (cubic_accumulator_run k).1^2 + (cubic_accumulator_run k).1^3)

/-- Every state of the loop is reachable. Relates definitions only. -/
theorem cubic_accumulator_run_reachable : ∀ k : Nat,
    Reachable cubic_accumulator_transition (pointEnv cubic_accumulator_initial) (pairEnv (cubic_accumulator_run k))
  | 0 => by
    have e : pairEnv (cubic_accumulator_run 0) = pointEnv cubic_accumulator_initial := by
      funext i
      match i with
      | 0 => simp [pairEnv, pointEnv, cubic_accumulator_initial, cubic_accumulator_run]
      | 1 => simp [pairEnv, pointEnv, cubic_accumulator_initial, cubic_accumulator_run]
      | i + 2 => simp [pairEnv, pointEnv, cubic_accumulator_initial]
    rw [e]
    exact .init
  | k + 1 => by
    have h := Reachable.step (cubic_accumulator_run_reachable k)
    have e : substEnv (pairEnv (cubic_accumulator_run k)) cubic_accumulator_transition = pairEnv (cubic_accumulator_run (k + 1)) := by
      funext i
      match i with
      | 0 =>
        simp [substEnv, pairEnv, cubic_accumulator_transition, cubic_accumulator_run, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
      | 1 =>
        simp [substEnv, pairEnv, cubic_accumulator_transition, cubic_accumulator_run, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] <;> omega
      | i + 2 => simp [substEnv, pairEnv, cubic_accumulator_transition, eval]
    rwa [e] at h

/-- **The claim in ordinary arithmetic**: at every iterate `(x0, x1)` of the
loop, the (scaled) invariant vanishes. Derived from `cubic_accumulator_invariant`. -/
theorem cubic_accumulator_concrete (k : Nat) (x0 x1 : Int) (h : cubic_accumulator_run k = (x0, x1)) :
    4 * x1 - x0^2 - 2 * x0^3 - x0^4 = 0 := by
  have hr := cubic_accumulator_invariant _ (cubic_accumulator_run_reachable k)
  rw [h] at hr
  simp [cubic_accumulator_cert, pairEnv, eval, monoEval, monoEvalFrom, setVar0, Int.pow_one, Int.pow_zero] at hr
  omega

/-! ### Negative controls

Each must be REJECTED. The exporter checked, before emitting, that the
prototype rejects it (where the prototype can express it) and that the
mirror of the Lean checker fails on exactly the conjunct named. -/

/-- the bundle's own mutation: constant 1 appended to the closed form (times the scale). Breaks: `base`. Prototype: rejects. -/
theorem power_sum_0_bundle_mutation_0_rejected :
    ({ scale := 1, formula := [([1], 1), ([0], 1)] } : RecCert).check [([0], 1)] [] = false := by decide

/-- the bundle's own mutation: constant 1 appended to the closed form (times the scale). Breaks: `base`. Prototype: rejects. -/
theorem power_sum_1_bundle_mutation_0_rejected :
    ({ scale := 2, formula := [([1], (-1)), ([2], 1), ([0], 2)] } : RecCert).check [([1], 1)] [] = false := by decide

/-- the bundle's own mutation: constant 1 appended to the closed form (times the scale). Breaks: `base`. Prototype: rejects. -/
theorem power_sum_2_bundle_mutation_0_rejected :
    ({ scale := 6, formula := [([1], 1), ([2], (-3)), ([3], 2), ([0], 6)] } : RecCert).check [([2], 1)] [] = false := by decide

/-- the bundle's own mutation: constant 1 appended to the closed form (times the scale). Breaks: `base`. Prototype: rejects. -/
theorem power_sum_3_bundle_mutation_0_rejected :
    ({ scale := 4, formula := [([2], 1), ([3], (-2)), ([4], 1), ([0], 4)] } : RecCert).check [([3], 1)] [] = false := by decide

/-- the bundle's own mutation: constant 1 appended to the closed form (times the scale). Breaks: `base`. Prototype: rejects. -/
theorem power_sum_4_bundle_mutation_0_rejected :
    ({ scale := 30, formula := [([1], (-1)), ([3], 10), ([4], (-15)), ([5], 6), ([0], 30)] } : RecCert).check [([4], 1)] [] = false := by decide

/-- closed form of sum_{i<=n} i, not sum_{i<n} i. Breaks: `step`. Prototype: rejects. -/
theorem power_sum_1_off_by_one_rejected :
    ({ scale := 2, formula := [([1], 1), ([2], 1)] } : RecCert).check [([1], 1)] [] = false := by decide

/-- power_sum_2's closed form offered for the step n^3. Breaks: `step`. Prototype: rejects. -/
theorem power_sum_2_wrong_step_rejected :
    ({ scale := 6, formula := [([1], 1), ([2], (-3)), ([3], 2)] } : RecCert).check [([3], 1)] [] = false := by decide

/-- scale 0 and formula 0: both identities hold, the claim would be vacuous. Breaks: `scale`. Prototype: cannot express. -/
theorem power_sum_1_zero_scale_rejected :
    ({ scale := 0, formula := [] } : RecCert).check [([1], 1)] [] = false := by decide

/-- initial value [([1], 0)] names the index variable. Breaks: `initial_free_of_index`. Prototype: cannot express. -/
theorem power_sum_0_initial_mentions_index_rejected :
    ({ scale := 1, formula := [([1], 1)] } : RecCert).check [([0], 1)] [([1], 0)] = false := by decide

/-- the bundle's own mutation: constant 1 appended to the invariant (times the scale). Breaks: `base`. Prototype: rejects. -/
theorem cubic_accumulator_bundle_mutation_0_rejected :
    ({ scale := 4, invariant := [([0, 1], 4), ([2, 0], (-1)), ([3, 0], (-2)), ([4, 0], (-1)), ([0, 0], 4)] } : InvCert).check [0, 0]
      [[([0, 0], 1), ([1, 0], 1)], [([0, 0], 1), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]] = false := by decide

/-- the zero polynomial: vanishes everywhere and is preserved by every map. Breaks: `nonzero`. Prototype: cannot express. -/
theorem cubic_accumulator_zero_invariant_rejected :
    ({ scale := 4, invariant := [] } : InvCert).check [0, 0]
      [[([0, 0], 1), ([1, 0], 1)], [([0, 0], 1), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]] = false := by decide

/-- scale 0: the invariant is unchanged, only the positivity conjunct fails. Breaks: `scale`. Prototype: cannot express. -/
theorem cubic_accumulator_zero_scale_rejected :
    ({ scale := 0, invariant := [([0, 1], 4), ([2, 0], (-1)), ([3, 0], (-2)), ([4, 0], (-1))] } : InvCert).check [0, 0]
      [[([0, 0], 1), ([1, 0], 1)], [([0, 0], 1), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]] = false := by decide

/-- transition s' = s + (n+1)^3 + 1: not conserved. Breaks: `step`. Prototype: rejects. -/
theorem cubic_accumulator_perturbed_transition_rejected :
    ({ scale := 4, invariant := [([0, 1], 4), ([2, 0], (-1)), ([3, 0], (-2)), ([4, 0], (-1))] } : InvCert).check [0, 0]
      [[([0, 0], 1), ([1, 0], 1)], [([0, 0], 2), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]] = false := by decide

/-- initial point (0, 1): invariant is -4 there, not 0. Breaks: `base`. Prototype: rejects. -/
theorem cubic_accumulator_wrong_initial_rejected :
    ({ scale := 4, invariant := [([0, 1], 4), ([2, 0], (-1)), ([3, 0], (-2)), ([4, 0], (-1))] } : InvCert).check [0, 1]
      [[([0, 0], 1), ([1, 0], 1)], [([0, 0], 1), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]] = false := by decide

/-- initial point of dimension 1 for a 2-state system. Breaks: `arity_initial`. Prototype: rejects. -/
theorem cubic_accumulator_short_initial_rejected :
    ({ scale := 4, invariant := [([0, 1], 4), ([2, 0], (-1)), ([3, 0], (-2)), ([4, 0], (-1))] } : InvCert).check [0]
      [[([0, 0], 1), ([1, 0], 1)], [([0, 0], 1), ([0, 1], 1), ([1, 0], 3), ([2, 0], 3), ([3, 0], 1)]] = false := by decide

end Forge.Checker
