#!/usr/bin/env python3
"""Head-to-head: forge_cone? against existing Lean tactics, on problems Forge did
not choose.

WHY. Everything measured before this showed Forge.Checker is SOUND; nothing
showed it is USEFUL. The earlier comparison ran on the prototype's own three
certificates, `grind` turned out to be no baseline at all (it cannot prove
0 <= x^2), and the 36-problem benchmark used certificates constructed first.
The decision this informs -- build the Gate 1 planner, or strengthen the search
first -- needs Forge's SEARCH measured against Mathlib's nonlinear tactics on a
problem set it did not generate. bench/tactics/problems.json is that set.

TOOLCHAIN. The only built Mathlib on this machine is for Lean v4.32.0, while
Forge pins v4.34.0. Forge.Checker is core-only and compiles unchanged on v4.32,
so the core modules are built with v4.32 into bench/tactics/.lake/build/lib
(ignored by git) and loaded next to Mathlib. The toolchain actually used is
recorded in the results.

FAIRNESS, stated so it can be checked:
  - every attempt is an Int statement, because Forge proves over Int;
  - Mathlib tactics get NO hints: `nlinarith [sq_nonneg ...]` would be handing
    them a certificate;
  - forge_cone? is told the problem's hypotheses by name, because its syntax
    requires them; nlinarith reads the same hypotheses from context;
  - every attempt runs under the same maxHeartbeats, sequentially
    (Elab.async false), so wall times are not distorted by parallel elaboration;
  - success is recorded by the attempt itself (a structured BENCH line) and not
    inferred from the absence of an error.

SAFETY. A kernel test earlier today grew without bound and helped fill the C:
drive. The Lean process tree is therefore run under a memory ceiling and a
time limit, and killed past either.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import psutil

ROOT = Path(__file__).resolve().parents[1]
BENCH = ROOT / "bench" / "tactics"
LIB = BENCH / ".lake" / "build" / "lib"
GEN = BENCH / ".lake" / "gen"
CORE = ["Poly", "Cone", "Reify", "Tactic", "Oracle"]
TACTICS = ["forge_cone?", "nlinarith", "positivity", "grind", "omega"]

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def toolchain_lean(version: str) -> Path:
    exe = Path.home() / ".elan" / "toolchains" / ("leanprover--lean4---" + version) / "bin"
    exe = exe / ("lean.exe" if os.name == "nt" else "lean")
    if not exe.exists():
        raise SystemExit("no Lean toolchain %s at %s" % (version, exe))
    return exe


def mathlib_libs(root: Path) -> list[str]:
    libs = sorted(str(p) for p in (root / ".lake" / "packages").glob("*/.lake/build/lib/lean"))
    if not any("mathlib" in p for p in libs):
        raise SystemExit("no built Mathlib under %s" % root)
    return libs


def build_core(lean: Path) -> None:
    """Compile Forge.Checker's core modules with the comparison toolchain."""
    (LIB / "Forge" / "Checker").mkdir(parents=True, exist_ok=True)
    env = dict(os.environ, LEAN_PATH=str(LIB))
    for mod in CORE:
        src = ROOT / "lean" / "Forge" / "Checker" / (mod + ".lean")
        out = LIB / "Forge" / "Checker" / (mod + ".olean")
        if out.exists() and out.stat().st_mtime > src.stat().st_mtime:
            continue
        print("building %s with %s" % (mod, lean.parent.parent.name))
        r = subprocess.run([str(lean), "-o", str(out), str(src)], env=env,
                           capture_output=True, text=True, encoding="utf-8", errors="replace",
                           cwd=str(ROOT / "lean"))
        if r.returncode != 0:
            raise SystemExit("building %s failed:\n%s" % (mod, (r.stdout + r.stderr)[-2000:]))


HEADER = r'''import Mathlib
import Forge.Checker.Oracle
/-
  GENERATED by tools/compare_tactics.py. Do not edit.
-/
set_option maxHeartbeats %(heartbeats)d
set_option Elab.async false
set_option linter.unusedVariables false
set_option linter.style.setOption false

open Lean Elab Tactic in
/-- Run a tactic, record success, wall time and Lean-side heartbeats as one
structured line, and fail loudly on failure. Runtime limits (heartbeats,
recursion) are caught and recorded as failures rather than crashing the run. -/
elab "bench_try " tag:str " => " t:tacticSeq : tactic => do
  let t0 ← IO.monoMsNow
  let h0 ← IO.getNumHeartbeats
  let res ← tryCatchRuntimeEx
    (do
      evalTactic t
      let gs ← getUnsolvedGoals
      pure (if gs.isEmpty then none else some "goals remain after the tactic"))
    (fun ex => do return some (← ex.toMessageData.toString))
  let ms := (← IO.monoMsNow) - t0
  let hb := (← IO.getNumHeartbeats) - h0
  match res with
  | none => logInfo m!"BENCH|{tag.getString}|ok|{ms}|{hb}|"
  | some why =>
    let why := String.join ((why.splitOn "\n").intersperse " ")
    logInfo m!"BENCH|{tag.getString}|fail|{ms}|{hb}|{why.take 240}"
    throwError "bench_try: {tag.getString} failed"

'''


def lean_ident(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def attempt(problem: dict, tactic: str) -> str:
    binders = "(%s : Int)" % " ".join(problem["vars"])
    hyps = " ".join("(%s : %s)" % (n, t) for n, t in problem["hyps"])
    if tactic == "forge_cone?":
        names = ", ".join(n for n, _ in problem["hyps"])
        tac = "forge_cone? [%s]" % names if names else "forge_cone?"
    else:
        tac = tactic
    name = "hh_%s_%s" % (problem["id"], lean_ident(tactic))
    tag = "%s|%s" % (problem["id"], tactic)
    return "theorem %s %s %s :\n    %s := by\n  bench_try \"%s\" => %s\n" % (
        name, binders, hyps, problem["goal"], tag, tac)


def run_guarded(cmd, env, cwd, mem_gb: float, seconds: int, log: Path) -> dict:
    with open(log, "w", encoding="utf-8", errors="replace") as out:
        p = subprocess.Popen(cmd, env=env, cwd=cwd, stdout=out, stderr=subprocess.STDOUT)
        proc = psutil.Process(p.pid)
        t0 = time.monotonic()
        peak = 0
        killed = None
        while p.poll() is None:
            time.sleep(1.0)
            try:
                tree = [proc] + proc.children(recursive=True)
                rss = sum(q.memory_info().rss for q in tree if q.is_running())
            except psutil.Error:
                rss = 0
            peak = max(peak, rss)
            if rss > mem_gb * 2**30:
                killed = "memory ceiling %.1f GB" % mem_gb
            elif time.monotonic() - t0 > seconds:
                killed = "time limit %d s" % seconds
            if killed:
                for q in reversed(tree):
                    try:
                        q.kill()
                    except psutil.Error:
                        pass
                break
        p.wait()
    return {"exit_code": p.returncode, "seconds": round(time.monotonic() - t0, 1),
            "peak_rss_gb": round(peak / 2**30, 2), "killed": killed}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--toolchain", default="v4.32.0")
    ap.add_argument("--mathlib-root", type=Path, default=Path("C:/ProveIt"))
    ap.add_argument("--heartbeats", type=int, default=400000)
    ap.add_argument("--mem-gb", type=float, default=12.0)
    ap.add_argument("--seconds", type=int, default=3600)
    ap.add_argument("--only", nargs="*", help="problem ids to run")
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "tactic-headtohead.json")
    args = ap.parse_args()

    toolchain_file = args.mathlib_root / "lean-toolchain"
    mathlib_toolchain = toolchain_file.read_text().strip() if toolchain_file.exists() else "unknown"
    if not mathlib_toolchain.endswith(args.toolchain):
        raise SystemExit("Mathlib at %s is built for %s, not %s"
                         % (args.mathlib_root, mathlib_toolchain, args.toolchain))
    lean = toolchain_lean(args.toolchain)
    build_core(lean)

    problems = json.loads((BENCH / "problems.json").read_text(encoding="utf-8"))["problems"]
    if args.only:
        problems = [p for p in problems if p["id"] in args.only]
    GEN.mkdir(parents=True, exist_ok=True)
    body = HEADER % {"heartbeats": args.heartbeats}
    body += "\n".join(attempt(p, t) for p in problems for t in TACTICS)
    gen = GEN / "HeadToHead.lean"
    gen.write_text(body, encoding="utf-8")

    sep = ";" if os.name == "nt" else ":"
    env = dict(os.environ, LEAN_PATH=sep.join([str(LIB)] + mathlib_libs(args.mathlib_root)))
    log = GEN / "HeadToHead.out"
    print("running %d attempts (%d problems x %d tactics) under %.0f GB / %d s"
          % (len(problems) * len(TACTICS), len(problems), len(TACTICS), args.mem_gb, args.seconds))
    run = run_guarded([str(lean), str(gen)], env, str(BENCH), args.mem_gb, args.seconds, log)
    text = log.read_text(encoding="utf-8", errors="replace")

    results: dict = {}
    for m in re.finditer(r"BENCH\|([^|]+)\|([^|]+)\|(ok|fail)\|(\d+)\|(\d+)\|(.*)", text):
        pid, tac, status, ms, hb, why = m.groups()
        results.setdefault(pid, {})[tac] = {
            "status": status, "ms": int(ms), "heartbeats": int(hb),
            **({"reason": why.strip()} if status == "fail" else {})}
    missing = [(p["id"], t) for p in problems for t in TACTICS
               if t not in results.get(p["id"], {})]

    def solved(t):
        return {p["id"] for p in problems if results.get(p["id"], {}).get(t, {}).get("status") == "ok"}

    summary = {t: len(solved(t)) for t in TACTICS}
    forge, nl, pos = solved("forge_cone?"), solved("nlinarith"), solved("positivity")
    mathlib_any = nl | pos
    size_refusals = [p["id"] for p in problems
                     if "MEASURED to check" in results.get(p["id"], {}).get("forge_cone?", {}).get("reason", "")]
    out = {
        "what": "forge_cone? versus Mathlib and core tactics on bench/tactics/problems.json.",
        "environment": {"toolchain": args.toolchain, "mathlib_root": str(args.mathlib_root),
                        "mathlib_toolchain": mathlib_toolchain, "max_heartbeats": args.heartbeats,
                        "forge_pins": "leanprover/lean4:v4.34.0 (core modules compile unchanged on v4.32)"},
        "run": run,
        "problems": len(problems),
        "solved": summary,
        "forge_only": sorted(forge - mathlib_any),
        "mathlib_only": sorted(mathlib_any - forge),
        "both": sorted(forge & mathlib_any),
        "neither_forge_nor_mathlib": sorted({p["id"] for p in problems} - forge - mathlib_any),
        "forge_refused_for_size": size_refusals,
        "attempts_without_a_result": missing,
        "results": results,
    }
    args.out.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print("run:", run)
    print("%-20s " % "problem" + " ".join("%-12s" % t for t in TACTICS))
    for p in problems:
        row = results.get(p["id"], {})
        cells = []
        for t in TACTICS:
            r = row.get(t)
            cells.append("%-12s" % ("-" if r is None else
                                    ("ok %dms" % r["ms"] if r["status"] == "ok" else "fail")))
        print("%-20s " % p["id"] + " ".join(cells))
    print("solved:", summary)
    print("forge only:", out["forge_only"], "| mathlib only:", out["mathlib_only"])
    if missing:
        print("NO RESULT for %d attempts, e.g. %s" % (len(missing), missing[:4]))
    return 0 if not missing and not run["killed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
