#!/usr/bin/env python3
"""Export the prototype's Farkas refutations for Forge.Checker.Farkas.

WHAT IS CERTIFIED. For the bundle family "Farkas refutation",
prototype/forge/io/decode.py calls `check_farkas(n, rows, bounds, multipliers)`,
which accepts exactly when the multipliers are nonnegative integers, one per
row, every row has `n` integer coefficients, sum lambda_i a_i = 0 and
sum lambda_i b_i < 0. `FarkasCert.check` in lean/Forge/Checker/Farkas.lean is the
same test, and `FarkasCert.sound` proves that a passing certificate leaves no
integer point satisfying every row.

Everything is an integer already, so nothing is rescaled: rows, bounds and
multipliers are emitted verbatim.

WHAT THIS SCRIPT CHECKS BEFORE EMITTING, for every positive and negative case:
  1. the prototype's own `verify` / `check_farkas`,
  2. an independent integer re-implementation of `FarkasCert.check`, conjunct by
     conjunct (count, width, sign, combination, strictness),
and it raises unless both reject and the conjunct designed to fail does fail.
Each negative control records every conjunct that fails (adding 1 to a
multiplier can also break strictness), and the file pins that the kernel
rejects it.

Negative controls, per record:
  mutation_mult0     the bundle's first mutation: multipliers[0] + 1   -> combination
  mutation_bounds    the bundle's second mutation: every bound + 1000 -> strictness
  zero_multipliers   all multipliers 0                                -> strictness
  extra_multiplier   one more multiplier than rows                    -> count
  negated            every multiplier negated                         -> sign, strictness
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lean_emit_guard import validate_ids, write_checked  # noqa: E402
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "prototype"))

from forge.io.decode import verify, mutations  # noqa: E402

FAMILY = "Farkas refutation"
CONJUNCTS = ("count", "width", "sign", "combination", "strictness")


# --------------------------------------------------------------------------
# Integer mirror of FarkasCert.check (Affine.lean's truncating dot and comb).
# --------------------------------------------------------------------------
def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def comb(p, a, W):
    out = [0] * p
    for aj, wj in reversed(list(zip(a, W))):
        out = [x + y for x, y in zip([aj * z for z in wj], out)]
    return out


def conjuncts(n, rows, bounds, lam) -> dict:
    return {
        "count": len(rows) == len(lam),
        "width": all(len(r) == n for r in rows),
        "sign": all(l >= 0 for l in lam),
        "combination": comb(n, lam, rows) == [0] * n,
        "strictness": dot(lam, bounds) < 0,
    }


def lean_check(n, rows, bounds, lam) -> bool:
    return all(conjuncts(n, rows, bounds, lam).values())


def record_of(n, rows, bounds, lam):
    return {"family": FAMILY, "input": {"n": n, "rows": rows, "bounds": bounds},
            "certificate": {"multipliers": lam}}


def unpack(rec):
    i = rec["input"]
    return i["n"], i["rows"], i["bounds"], rec["certificate"]["multipliers"]


# --------------------------------------------------------------------------
# Lean text.
# --------------------------------------------------------------------------
def li(v: int) -> str:
    return str(v) if v >= 0 else "(%d)" % v


def lvec(v) -> str:
    return "[%s]" % ", ".join(li(x) for x in v)


def lrows(rows, bounds) -> str:
    return "[%s]" % ", ".join("⟨%s, %s⟩" % (lvec(r), li(b)) for r, b in zip(rows, bounds))


def lean_ident(s: str) -> str:
    return s


def row_text(row, bound) -> str:
    terms = []
    for j, a in enumerate(row):
        if a == 0:
            continue
        v = "x%d" % j
        terms.append(v if a == 1 else "-%s" % v if a == -1 else "%s * %s" % (li(a), v))
    return "%s ≤ %s" % (" + ".join(terms) if terms else "0", li(bound))


HEADER = '''import Forge.Checker.Farkas
/-
  GENERATED by tools/export_lean_farkas.py from the prototype's certificate
  bundle (family "Farkas refutation"). Do not edit by hand; regenerate.

  Each certificate below was accepted by the prototype's `check_farkas` and by an
  integer re-implementation of `FarkasCert.check` in the exporter, and is
  accepted here again by the Lean kernel via `decide`. No `native_decide`.

  `_infeasible` is `FarkasCert.sound` applied to `_checks`: no decision
  procedure is involved. `_concrete` restates it in ordinary arithmetic. Each
  row lemma `_row_i` uses `omega` to identify ONE hypothesis with its unfolded
  constraint, and sees only that hypothesis; the refutation itself comes from the
  certificate. (These systems are small enough that `omega` could refute them
  outright; the point here is that the prototype's certificate is what the
  kernel checks.)

  Negative controls: the bundle's two mutations, plus controls that each break
  named conjuncts of the checker, as recorded in results/lean-farkas-corpus.json.
-/

namespace Forge.Checker.FarkasCorpus
open Forge.Checker.Lin Forge.Checker.Farkas
'''


def emit_positive(rid, n, rows, bounds, lam):
    m = lean_ident(rid)
    xs = ["x%d" % j for j in range(n)]
    binders = " ".join(xs)
    L = ["/-! ### `%s` --- %d constraints in %d variables -/" % (rid, len(rows), n), ""]
    L.append("def %s_rows : List Constraint := %s" % (m, lrows(rows, bounds)))
    L.append("def %s_cert : FarkasCert := ⟨%s⟩" % (m, lvec(lam)))
    L.append("")
    L.append("/-- The checker accepts, by kernel reduction. -/")
    L.append("theorem %s_checks : %s_cert.check %d %s_rows = true := by decide" % (m, m, n, m))
    L.append("")
    L.append("/-- No integer point satisfies every row. -/")
    L.append("theorem %s_infeasible (x : List Int) : ¬ ∀ r ∈ %s_rows, r.Holds x :=" % (m, m))
    L.append("  FarkasCert.sound %d %s_rows %s_cert %s_checks x" % (n, m, m, m))
    L.append("")
    for i, (r, b) in enumerate(zip(rows, bounds)):
        L.append("theorem %s_row_%d (%s : Int) (h : %s) :" % (m, i, binders, row_text(r, b)))
        L.append("    Constraint.Holds [%s] ⟨%s, %s⟩ := by" % (", ".join(xs), lvec(r), li(b)))
        L.append("  simp only [Constraint.Holds, dot]")
        L.append("  omega")
        L.append("")
    hs = ["h%d" % i for i in range(len(rows))]
    L.append("/-- The same fact in ordinary arithmetic. -/")
    L.append("theorem %s_concrete (%s : Int) :" % (m, binders))
    L.append("    ¬ (%s) := by" % " ∧\n       ".join(row_text(r, b) for r, b in zip(rows, bounds)))
    L.append("  intro ⟨%s⟩" % ", ".join(hs))
    L.append("  apply %s_infeasible [%s]" % (m, ", ".join(xs)))
    L.append("  intro r hr")
    L.append("  simp only [%s_rows, List.mem_cons, List.not_mem_nil, or_false] at hr" % m)
    L.append("  rcases hr with %s" % " | ".join(["rfl"] * len(rows)))
    for i in range(len(rows)):
        L.append("  · exact %s_row_%d %s h%d" % (m, i, binders, i))
    L.append("")
    return L


def emit_negative(rid, tag, why, n, rows, bounds, lam, failing):
    m = "%s_%s" % (lean_ident(rid), tag)
    L = ["/-- NEGATIVE CONTROL `%s`: %s Failing conjuncts: %s. -/" % (tag, why, ", ".join(failing))]
    L.append("def %s_rows : List Constraint := %s" % (m, lrows(rows, bounds)))
    L.append("def %s_cert : FarkasCert := ⟨%s⟩" % (m, lvec(lam)))
    L.append("theorem %s_rejected : %s_cert.check %d %s_rows = false := by decide" % (m, m, n, m))
    L.append("")
    return L


def negatives(rec, n, rows, bounds, lam):
    muts = mutations(rec)
    if len(muts) != 2:
        raise SystemExit("expected two bundle mutations, got %d" % len(muts))
    out = []
    for tag, mut, expect in [("mutation_mult0", muts[0], {"combination"}),
                             ("mutation_bounds", muts[1], {"strictness"})]:
        if verify(mut):
            raise SystemExit("%s: bundle mutation accepted by the prototype" % tag)
        why = ("the bundle's mutation `multipliers[0] + 1`." if tag == "mutation_mult0"
               else "the bundle's mutation, every bound + 1000.")
        out.append((tag, why) + tuple(unpack(mut)) + (expect,))
    out.append(("zero_multipliers", "all multipliers 0; the combination is `0 ≤ 0`.",
                n, rows, bounds, [0] * len(lam), {"strictness"}))
    out.append(("extra_multiplier", "one more multiplier than rows.",
                n, rows, bounds, lam + [0], {"count"}))
    out.append(("negated", "every multiplier negated.",
                n, rows, bounds, [-v for v in lam], {"sign", "strictness"}))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bundle", type=Path,
                    default=ROOT / "prototype" / "results" / "certificates.json")
    ap.add_argument("--out", type=Path,
                    default=ROOT / "lean" / "Forge" / "Checker" / "FarkasCorpus.lean")
    ap.add_argument("--json", type=Path,
                    default=ROOT / "results" / "lean-farkas-corpus.json")
    args = ap.parse_args()

    records = json.loads(args.bundle.read_text(encoding="utf-8"))
    wanted = [r for r in records if r["family"] == FAMILY]
    # Ids are interpolated into generated Lean: refuse, never escape.
    validate_ids([r["id"] for r in wanted])
    if not wanted:
        raise SystemExit("no Farkas refutations in the bundle")

    body, summary, names = [], [], []
    for rec in wanted:
        n, rows, bounds, lam = unpack(rec)
        if not verify(rec) or not lean_check(n, rows, bounds, lam):
            raise SystemExit("%s: prototype and integer mirror do not both accept" % rec["id"])
        body += emit_positive(rec["id"], n, rows, bounds, lam)
        m = lean_ident(rec["id"])
        names += ["%s_checks" % m, "%s_infeasible" % m, "%s_concrete" % m]
        controls = []
        for tag, why, cn, crows, cbounds, clam, expect in negatives(rec, n, rows, bounds, lam):
            try:
                py = verify(record_of(cn, crows, cbounds, clam))
            except Exception as exc:  # a decoder refusal is a rejection too
                py = False
                why += " (decoder: %s)" % exc
            failing = sorted(k for k, ok in conjuncts(cn, crows, cbounds, clam).items() if not ok)
            if py or not expect <= set(failing):
                raise SystemExit("%s/%s: control not as designed (python=%s failing=%s)"
                                 % (rec["id"], tag, py, failing))
            body += emit_negative(rec["id"], tag, why, cn, crows, cbounds, clam,
                                  [c for c in CONJUNCTS if c in failing])
            names.append("%s_%s_rejected" % (m, tag))
            controls.append({"control": tag, "prototype_accepts": py,
                             "failing_conjuncts": [c for c in CONJUNCTS if c in failing]})
        summary.append({"id": rec["id"], "variables": n, "constraints": len(rows),
                        "multipliers": lam, "negative_controls": controls})

    text = HEADER + "\n" + "\n".join(body)
    text += "".join("#print axioms %s\n" % x for x in names)
    text += "\nend Forge.Checker.FarkasCorpus\n"
    write_checked(args.out, text)

    args.json.write_text(json.dumps({
        "what": ("Every Farkas refutation in the prototype bundle, emitted as Int data for "
                 "Forge.Checker.Farkas, with negative controls. Each verdict is checked by "
                 "the prototype's check_farkas and by an integer mirror of FarkasCert.check "
                 "before emission, and again by the Lean kernel when FarkasCorpus.lean is "
                 "elaborated."),
        "generated_lean": "lean/Forge/Checker/FarkasCorpus.lean",
        "checked_by": "kernel reduction via `decide`; native_decide is not used",
        "certificates": summary,
    }, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print("wrote %s" % args.out)
    for s in summary:
        print("  %-18s n=%d rows=%d multipliers=%s controls=%d" % (
            s["id"], s["variables"], s["constraints"], s["multipliers"],
            len(s["negative_controls"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
