#!/usr/bin/env python3
"""The `forge` baseline suite: every goal, every mode, pinned.

WHY. Gate 1's first exit criterion is that the restricted mode "reproduces a
pinned baseline suite without introducing new axioms". The first milestone
pinned three goals. This suite pins 76: the 40 nonlinear Int inequalities of
the tactic head-to-head (bench/tactics/problems*.json) and 36 goals of other
kinds (bench/forge/goals.json) -- closed arithmetic, linear arithmetic,
propositional and equational reasoning, simple data, and a few true goals no
worker was expected to reach.

MODES.
  restricted  `forge` with forge.restricted: decide, omega, grind. No Python.
  oracle      `forge` in full: decide, omega, forge_cone?, grind.
  each        every worker ALONE on every goal, with rollback between them.
              This is what shows whether the fixed ORDER costs anything: a
              goal a later worker would close faster, or one an earlier worker
              wastes time failing on.

For each goal and mode the record holds the worker that closed it, every
attempt before it with its time and rejection reason, and the axioms of the
accepted proof, read from `#print axioms`. Results go to
results/forge-baseline.json.

PINNING. `--pin` writes the closing worker per goal and mode, and the axioms of
each proof, to bench/forge/expected.json. `--check` compares a fresh run with
that file and exits 1 on any difference, so the baseline cannot drift
silently. Times are never pinned. The per-goal PREDICTIONS in goals.json were
written before any run and are reported against the outcome, not pinned.

Everything runs core-only on the pinned toolchain, one Lean process per mode,
under the repository's usual memory ceiling and time limit.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import compare_tactics as ct  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

LEAN = ROOT / "lean"
LIB = LEAN / ".lake" / "build" / "lib" / "lean"
GEN = LEAN / ".lake" / "gen"
EXPECTED = ROOT / "bench" / "forge" / "expected.json"
MODES = ("restricted", "oracle", "each")

HEADER = r'''import Forge.Frontend
/-
  GENERATED by tools/forge_baseline.py. Do not edit.
-/
set_option maxHeartbeats %(heartbeats)d
set_option Elab.async false
set_option linter.unusedVariables false
%(mode_options)s
namespace Forge.Baseline

open Lean Elab Tactic Forge.Frontend

def clean (s : String) : String :=
  ((s.splitOn "\n").intersperse " " |> String.join).replace "|" "/" |>.replace ";;" ";"

def attemptText (a : Attempt) : String :=
  s!"{a.worker}~{if a.accepted then "ok" else "no"}~{a.ms}~{(clean a.reason).take 200}"

/-- Run `forge`'s loop and log it as one structured line. -/
elab "forge_bench " tag:str : tactic => do
  let o ← runForge (← getMainGoal)
  let atts := ";;".intercalate (o.attempts.toList.map attemptText)
  match o.closedBy with
  | some (name, _) => logInfo m!"FORGE|{tag.getString}|closed|{name}|{atts}"
  | none =>
    logInfo m!"FORGE|{tag.getString}|open||{atts}"
    throwError "forge_bench: {tag.getString} open"

/-- Run EVERY worker alone on the goal, restoring the state after each. The
goal is then left for the caller; the generated file admits it, because this
mode measures workers and proves nothing. -/
elab "forge_each " tag:str : tactic => do
  let goal ← getMainGoal
  let mut out : Array String := #[]
  for (name, stx) in ← workers do
    let saved ← saveState
    let t0 ← IO.monoMsNow
    let r ← runWorker goal stx
    let ms := (← IO.monoMsNow) - t0
    out := out.push (attemptText ⟨name, r.isNone, r.getD "", ms⟩)
    saved.restore (restoreInfo := true)
  logInfo m!"FORGE|{tag.getString}|each||{";;".intercalate out.toList}"

'''


def load_goals() -> list[dict]:
    goals = []
    for f in ("problems.json", "problems_heldout.json"):
        for p in json.loads((ROOT / "bench" / "tactics" / f).read_text(encoding="utf-8"))["problems"]:
            binders = "(%s : Int)" % " ".join(p["vars"])
            hyps = " ".join("(%s : %s)" % (n, t) for n, t in p["hyps"])
            goals.append({"id": p["id"], "class": "nonlinear_int", "source": "bench/tactics/" + f,
                          "statement": "%s %s : %s" % (binders, hyps, p["goal"]),
                          "expected_worker": "forge_cone?"})
    extra = json.loads((ROOT / "bench" / "forge" / "goals.json").read_text(encoding="utf-8"))["goals"]
    for g in extra:
        goals.append({**g, "source": "bench/forge/goals.json"})
    ids = [g["id"] for g in goals]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate goal ids")
    for i in ids:
        if not re.fullmatch(r"[A-Za-z0-9_]+", i):
            raise SystemExit("goal id %r is not a plain identifier" % i)
    return goals


def generate(mode: str, goals: list[dict], heartbeats: int) -> str:
    opts = {"restricted": "set_option forge.restricted true\n",
            "oracle": "", "each": ""}[mode]
    text = HEADER % {"heartbeats": heartbeats, "mode_options": opts}
    for g in goals:
        name = "fb_%s" % g["id"]
        if mode == "each":
            text += "theorem %s %s := by\n  forge_each \"%s\"\n  admit\n\n" % (name, g["statement"], g["id"])
        else:
            text += "theorem %s %s := by\n  forge_bench \"%s\"\n\n" % (name, g["statement"], g["id"])
            text += "#print axioms %s\n\n" % name
    return text + "end Forge.Baseline\n"


def parse(text: str) -> tuple[dict, dict]:
    records = {}
    for m in re.finditer(r"FORGE\|([A-Za-z0-9_]+)\|(closed|open|each)\|([^|]*)\|(.*)", text):
        gid, status, worker, atts = m.groups()
        attempts = []
        for a in atts.strip().split(";;") if atts.strip() else []:
            w, ok, ms, why = (a.split("~", 3) + ["", "", ""])[:4]
            attempts.append({"worker": w, "accepted": ok == "ok", "ms": int(ms) if ms.isdigit() else None,
                             **({"reason": why} if why else {})})
        records[gid] = {"status": status, **({"closed_by": worker} if worker else {}),
                        "attempts": attempts}
    axioms = {}
    for m in re.finditer(r"'Forge\.Baseline\.fb_([A-Za-z0-9_]+)' depends on axioms: \[([^\]]*)\]", text):
        axioms[m.group(1)] = [a.strip() for a in m.group(2).split(",") if a.strip()]
    for m in re.finditer(r"'Forge\.Baseline\.fb_([A-Za-z0-9_]+)' does not depend on any axioms", text):
        axioms[m.group(1)] = []
    return records, axioms


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--modes", nargs="*", default=list(MODES), choices=MODES)
    ap.add_argument("--heartbeats", type=int, default=400000)
    ap.add_argument("--mem-gb", type=float, default=8.0)
    ap.add_argument("--seconds", type=int, default=5400)
    ap.add_argument("--pin", action="store_true", help="write bench/forge/expected.json")
    ap.add_argument("--check", action="store_true", help="fail if the run differs from expected.json")
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "forge-baseline.json")
    args = ap.parse_args()

    goals = load_goals()
    toolchain = (LEAN / "lean-toolchain").read_text().strip()
    lean = ct.toolchain_lean(toolchain.split(":")[-1])
    env = dict(os.environ, LEAN_PATH=str(LIB))
    GEN.mkdir(parents=True, exist_ok=True)

    previous = json.loads(args.out.read_text(encoding="utf-8")) if args.out.exists() else {}
    modes_out = dict(previous.get("modes", {}))
    for mode in args.modes:
        src = GEN / ("ForgeBaseline_%s.lean" % mode)
        src.write_text(generate(mode, goals, args.heartbeats), encoding="utf-8")
        log = GEN / ("ForgeBaseline_%s.out" % mode)
        print("mode %s: %d goals" % (mode, len(goals)))
        # cwd is the repository root so the oracle finds tools/forge_oracle.py.
        run = ct.run_guarded([str(lean), str(src)], env, str(ROOT), args.mem_gb, args.seconds, log)
        text = log.read_text(encoding="utf-8", errors="replace")
        records, axioms = parse(text)
        missing = [g["id"] for g in goals if g["id"] not in records]
        for gid, ax in axioms.items():
            if gid in records and records[gid]["status"] == "closed":
                records[gid]["axioms"] = ax
        # Cross-check: a closed goal must have its axioms printed, and an open one
        # must have produced an error for its theorem.
        no_axioms = [g for g, r in records.items() if r["status"] == "closed" and "axioms" not in r]
        modes_out[mode] = {"run": run, "records": records, "missing": missing,
                           "closed_without_axiom_line": no_axioms}
        closed = sum(1 for r in records.values() if r["status"] == "closed")
        print("  %s; closed %d, open %d, missing %d" % (
            run, closed, sum(1 for r in records.values() if r["status"] == "open"), len(missing)))

    summary = {}
    for mode, m in modes_out.items():
        recs = m["records"]
        if mode == "each":
            summary[mode] = {w: sum(1 for r in recs.values() for a in r["attempts"]
                                    if a["worker"] == w and a["accepted"])
                             for w in ("decide", "omega", "forge_cone?", "grind")}
        else:
            by = {}
            for r in recs.values():
                if r["status"] == "closed":
                    by[r["closed_by"]] = by.get(r["closed_by"], 0) + 1
            summary[mode] = {"closed": sum(by.values()), "open": sum(1 for r in recs.values() if r["status"] == "open"),
                             "closed_by": by}
    out = {
        "what": "forge on 76 goals in three modes; see tools/forge_baseline.py.",
        "toolchain": toolchain,
        "max_heartbeats": args.heartbeats,
        "goals": [{k: g[k] for k in ("id", "class", "source", "statement", "expected_worker")} for g in goals],
        "summary": summary,
        "modes": modes_out,
    }
    args.out.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=1))

    pinned = {mode: {gid: {"closed_by": r.get("closed_by"), "axioms": r.get("axioms")}
                     for gid, r in sorted(modes_out[mode]["records"].items())}
              for mode in ("restricted", "oracle") if mode in modes_out}
    if args.pin:
        EXPECTED.write_text(json.dumps({
            "what": ("The pinned forge baseline: for each goal and mode, the worker that closes it "
                     "(null if none) and the axioms of the accepted proof. Written by "
                     "tools/forge_baseline.py --pin; checked by --check. Times are not pinned."),
            "pinned": pinned}, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print("pinned %s" % EXPECTED)
    bad = False
    for mode in args.modes:
        if modes_out[mode]["missing"] or modes_out[mode]["closed_without_axiom_line"] or modes_out[mode]["run"]["killed"]:
            print("INCOMPLETE %s: missing=%s no_axiom_line=%s killed=%s" % (
                mode, modes_out[mode]["missing"][:5], modes_out[mode]["closed_without_axiom_line"][:5],
                modes_out[mode]["run"]["killed"]))
            bad = True
    if args.check:
        expected = json.loads(EXPECTED.read_text(encoding="utf-8"))["pinned"]
        for mode in args.modes:
            if mode not in expected:
                continue
            for gid in sorted(set(expected[mode]) | set(pinned.get(mode, {}))):
                e, a = expected[mode].get(gid), pinned.get(mode, {}).get(gid)
                if e != a:
                    print("DRIFT %s/%s: pinned %s, now %s" % (mode, gid, e, a))
                    bad = True
        print("check: %s" % ("FAILED" if bad else "matches the pinned baseline"))
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
